### ISSUE TITLE
Pool reply duplicated json...

### ISSUE THREAD

**Issue by jq8778** [sebseb7/cryptonote-proxy#2]
Seems if we push huge hash rate (eg. 100kh) to a pool, the pool will reply duplicated json...
Please check the following log...
2018-03-27T08:52:29.499Z - debug: received from pool (grft_easyhash):{"id":54,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}
{"id":55,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}
{"id":56,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}} (x)
2018-03-27T08:52:29.500Z - error:  SyntaxError: Unexpected token {
    at Object.parse (native)
    at Socket.<anonymous> (/home/root/cryptonote-proxy/proxy.js:74:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:540:20)

The json string '{"id":54,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}
{"id":55,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}
{"id":56,"jsonrpc":"2.0","error":null,"result":{"status":"OK"}}'
will make error on JSON.parse...

**Comment by sebseb7** [comment]
what pool, what mining software?

**Comment by jq8778** [comment]
Xmrig-proxy with xmr-stak 2.0
It's happening on a lot of pools such as easyhash.io, graftpool.net,etc...
Also, on the miner side sometimes i get:
![asdww](https://user-images.githubusercontent.com/18402588/37974567-d1891302-320f-11e8-9fea-f348816c6966.jpg)

**Comment by sebseb7** [comment]
come here for investigation of the problem: https://discord.gg/h7JDXpT
