### ISSUE TITLE
getting an error pools user is not iterable

### ISSUE THREAD

**Issue by zeilercd** [sebseb7/cryptonote-proxy#6]
Hello.  3 days i've been trying to get my config.json file to work... i had an extra ,   woops! lol
Ok - so i'm all excited - now when i click the run.sh - i get the little command window that stays open and says 2018-05-26T06:51:11.935Z - info: start http interface on port 2350
2018-05-26T06:51:11.944Z - info: start mining proxy on port 2349
so i open the localport:2350
And i get a page that has a load and a reload config button
i press load and WOOPS
2018-05-26T06:51:15.944Z - error:  TypeError: pools[user] is not iterable
   at Socket.<anonymous> (C:\cryptonote-proxy\proxy.js:315:25)
   at emitOne (events.js:116:13)
   at Socket.emit (events.js:211:7)
   at C:\cryptonote-proxy\node_modules\socket.io\lib\socket.js:528:12
   at _combinedTickCallback (internal/process/next_tick.js:131:7)
   at process._tickCallback (internal/process/next_tick.js:180:9)
so....
for grins and giggles... i rename MY config.json file as a txt file
and i copy the example config.json_example as just config.json and re-run run.sh...
it loads the cmd box and says info: start http interface on port 2350 and mining on 2349...
i reload the localport:2350 and again - white page with load and reload config buttons
hit load and exact same error
2018-05-26T06:51:15.944Z - error:  TypeError: pools[user] is not iterable
   at Socket.<anonymous> (C:\cryptonote-proxy\proxy.js:315:25)
   at emitOne (events.js:116:13)
   at Socket.emit (events.js:211:7)
   at C:\cryptonote-proxy\node_modules\socket.io\lib\socket.js:528:12
   at _combinedTickCallback (internal/process/next_tick.js:131:7)
   at process._tickCallback (internal/process/next_tick.js:180:9)

help? what has gone wrong and how can i fix this?
I would REALLY love to use this one click pool changer :)

**Comment by zeilercd** [comment]
OMG
it was as simple as typing what i had for usera into the top (unnoticed) text box before hitting load
THANKS ALL for reading
And... hope you got a good giggle, i am... sigh silly me
